name: CommandCooldown
version: '${version}'
main: dev.nxms.commandcooldown.CommandCooldown
api-version: '1.21'
description: Anty-spam komend - globalne i indywidualne opóźnienia
author: nxmsdev

commands:
  opoznieniekomend:
    description: Ustawienia opóźnień komend
    usage: /<command> <pomoc|przeladuj|ustaw|usun|lista|info>
    aliases: [ok]

permissions:
  commandcooldown.admin:
    description: Dostęp do wszystkich komend administracyjnych
    default: op
    children:
      commandcooldown.reload: true
      commandcooldown.set: true
      commandcooldown.remove: true
      commandcooldown.list: true
      commandcooldown.info: true

  commandcooldown.reload:
    description: Przeładowanie configu i messages
    default: op

  commandcooldown.set:
    description: Ustawienie opóźnień
    default: op

  commandcooldown.remove:
    description: Usuwanie opóźnień komend
    default: op

  commandcooldown.list:
    description: Lista komend z opóźnieniami
    default: op

  commandcooldown.info:
    description: Podgląd aktualnego opóźnienia
    default: true

  commandcooldown.bypass:
    description: Omija opóźnienia komend
    default: op