name: OpoznienieKomend
version: '${version}'
main: dev.nxms.commandcooldown.CommandCooldown
api-version: '1.21'
description: Globalny anty-spam komend
author: nxmsdev

commands:
  opoznieniekomend:
    description: Ustawienia globalnego opóźnienia komend
    usage: /<command> <pomoc|przeladuj|ustaw|info>
    aliases: [ok]

permissions:
  commandcooldown.admin:
    description: Dostęp do wszystkich komend administracyjnych
    default: op
    children:
      commandcooldown.reload: true
      commandcooldown.set: true
      commandcooldown.info: true

  commandcooldown.reload:
    description: Przeładowanie configu i messages
    default: op

  commandcooldown.set:
    description: Ustawienie globalnego opóźnienia
    default: op

  commandcooldown.info:
    description: Podgląd aktualnego opóźnienia
    default: true

  commandcooldown.bypass:
    description: Omija globalne opóźnienie komend
    default: op